/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 src/assets/Butterfly.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Butterfly(props) {
  const { nodes, materials } = useGLTF("./models/butterfly/Butterfly.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Butterfly1-Mesh"].geometry}
        material={materials.Mat}
      />
      <mesh
        geometry={nodes["Butterfly1-Mesh_1"].geometry}
        material={materials["Mat.1"]}
      />
      <mesh
        geometry={nodes["Butterfly1-Mesh_2"].geometry}
        material={materials["Mat.2"]}
      />
    </group>
  );
}

useGLTF.preload("./models/butterfly/Butterfly.glb");
