/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/dog/dog.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dog(props) {
  const { nodes, materials } = useGLTF("./models/dog/Dog.glb");

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes["Node-Mesh"].geometry} material={materials.mat19} />
      <mesh
        geometry={nodes["Node-Mesh_1"].geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes["Node-Mesh_2"].geometry}
        material={materials.mat23}
      />
    </group>
  );
}

useGLTF.preload("./models/dog/Dog.glb");
